### ISSUE TITLE
Error when running identify_empty_drops(): "scale estimate is zero for input data"

### ISSUE THREAD

**Issue by ayshwaryas** [powellgenomicslab/DropletQC#3] opened 2022-05-14 23:30 UTC
I am trying to run DropletQC on the [_Tabula muris_](https://www.nature.com/articles/s41586-020-2496-1) lung and heart datasets and I run into the same error when identifying empty drops. The 10X Cellranger outputs (BAM, BAI, barcode.tsv and renames with path as required by DropletQC) were downloaded from [the _Tabula muris_ Amazon bucket](https://s3.console.aws.amazon.com/s3/buckets/czb-tabula-muris-senis?prefix=10x/3_month/&region=us-west-2 ) for the samples:
Heart_and_Aorta:
10X_P7_4
Lung samples:
10X_P7_8
10X_P7_9

Here is an example for 10X_P7_8:

The nuclear fraction was estimated using the command:

`  p7_8_nf1 <- nuclear_fraction_tags(outs = "~/10X_P7_8/",tiles = 1, cores = 12)
`
Then, I attempted to identify empty droplets and run into the error

```
> head(tmlung_p7_9.nf.umi)`
  p7_98_nf1 umi
1         0   0
2         0   0
3         0   0
4         0  42
5         0   0
6         0   1
>  tmlung_p7_9.ed <- identify_empty_drops(nf_umi=tmlung_p7_9.nf.umi)
Error in dpik(x = x, level = nstage, gridsize = bgridsize) : 
  scale estimate is zero for input data
```

Any suggestions on what input parameters to tune? Thank you.

**Comment by WalterMuskovic** [comment] 2022-05-27 04:01
Hi @ayshwaryas  - sorry for the delay! I just saw your message today. The issue above is caused by most of the cell barcodes having 0 UMIs. There's >700,000 barcodes in the barcodes.tsv file (!) but < 1,000 cells were captured for this sample. The code below is the approach I would recommend for this sample:
```
# Load R packages ---------------------------------------------------------
library(Seurat)
library(tidyverse)
library(DropletQC)

# Load data ---------------------------------------------------------------
list.files()
# "barcodes.gencode.vM19.tsv"    "possorted_genome_bam.bam"    
# "possorted_genome_bam.bam.bai" "raw_gene_bc_matrices_h5.h5" 

# Import counts, create a Seurat object, filter cells with < 1000 UMIs
tm <- Read10X_h5("raw_gene_bc_matrices_h5.h5") %>%
  CreateSeuratObject(project = "10X_P7_8") %>%
  subset(nCount_RNA>1000)
nrow(tm)
# 692
# Very few cells in this sample

# Check what's in the barcodes file
cb <- read_tsv("barcodes.gencode.vM19.tsv", col_names="cb")
nrow(cb)
# 737280
# >> than the number of cells

# Run DropletQC -----------------------------------------------------------
# Calculate the nuclear fraction
nf <- nuclear_fraction_tags(bam = "possorted_genome_bam.bam",
                      barcodes = colnames(tm),
                      cores = 16)

# Add to the Seurat object
tm <- AddMetaData(tm, nf)

# Identify empty droplets
ed <- tm@meta.data %>%
  select(nuclear_fraction, nCount_RNA) %>%
  identify_empty_drops() %>%
  select(cell_status)

# Add to the Seurat object
tm <- AddMetaData(tm, ed)

# Plot
ggplot(tm@meta.data,
       aes(x=nuclear_fraction, y=log10(nCount_RNA), colour=cell_status)) +
  geom_point()
  ```
 
![nf_umi_plot](https://user-images.githubusercontent.com/38969859/170626557-e7067406-8e04-4fa8-8b39-a040ab201b6d.png)
 
Hope that helps, let me know and sorry again for the delay! I've updated my notifications so I should get an email now when someone posts an issue.

**Comment by WalterMuskovic** [comment] 2022-07-11 03:58
Hi @ayshwaryas ,

I hope that the reply above solved your problem. I'm going to close this issue for now, but please let me know if you need a hand with anything else.

**Closed as completed by WalterMuskovic** 2022-07-11 03:58 UTC
